creation_rules:
  - path_regex: chart/values\.secrets\.yaml$
    encrypted_regex: "^secrets$"
    age: age1nl33y6r6kuv5wz4svfeua48kd7vgz2l9vyqfvy50akmlmkf3a92sfl90s0
  - path_regex: secrets/.*\.yaml$
    encrypted_regex: "^(data|stringData)$"
    age: age1nl33y6r6kuv5wz4svfeua48kd7vgz2l9vyqfvy50akmlmkf3a92sfl90s0
