services:
  app:
    image: dtj
    build: .
    volumes:
      - './data/static:/src/static'
      - './data/media:/src/media'
      - './data/db.sqlite3:/src/db.sqlite3'
  proxy:
    image: nginx:alpine
    expose:
      - 8001
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/static:/dstatic
      - ./data/media:/dmedia
    labels:
      # because nginx exposes by default port 80 and I expose 8001 in addition
      # to it, traefik needs to know what to redirect to https://doc.traefik.io/traefik/providers/docker/#port-detection
      - 'traefik.http.services.http-0-oocw04c.loadbalancer.server.port=8001' 
