services:
  app:
    image: dtj
    build: .
    volumes:
      - './data/static:/src/static'
      - './data/media:/src/media'
      - './data/db.sqlite3:/src/db.sqlite3'
    environment:
      DJANGO_SECRET_KEY: a
    ports:
      - 8000:8000
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/static:/dstatic
      - ./data/media:/dmedia
