version: '3.7'
services:
  sovazluticeApp:
    restart: unless-stopped
    networks:
      - caddy
    image: dtj
    build: .
    expose:
      - 8000
    environment:
      ENVIRONMENT: production
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    working_dir: /
    volumes:
      - ./django:/django
      # WARNING: this is in the dockerfile as well!
      - ./gunicorn_start:/gunicorn_start
  sovazlutice:
    image: nginx:alpine
    restart: unless-stopped
    labels:
      caddy: "sovazlutice.eu www.sovazlutice.eu"
      caddy.reverse_proxy: "{{upstreams 8001}}"
    networks:
      - caddy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./django/static:/dstatic
      - ./django/media:/dmedia
networks:
  caddy:
    external: true
